language: en
recipe: default.v1

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: EntitySynonymMapper
- name: CRFEntityExtractor
- name: LogisticRegressionClassifier
- name: ResponseSelector
  epochs: 50
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 50
- name: TEDPolicy
  max_history: 5
  epochs: 50
  constrain_similarities: true
assistant_id: 20250616-131952-lenient-lumber
